author: 薯条 # 作者
description: 薯条的博客
keyword: hexo-theme, vuejs

excerpt_link: 阅读全文

menu:
 首页: /
 标签: /tags/
 归档: /archives/
 项目: /project/
 关于我: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: true

# comment
# you can set utterances, gitment, uyan or disqus
comment: utterances

# utterances config
utterances_repo:                # e.g. GitHubAccount/RepoForUtterances
utterances_issue_term: pathname # you can see other available options at 'https://utteranc.es/'
utterances_theme: github-light  # you can see other available options at 'https://utteranc.es/'

# gitment config
gitment_owner: 
gitment_repo: 
gitment_oauth_id: 
gitment_oauth_secret: 

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics: 
# disqus config
disqus_shortname: 

about: 
  banner: ""
  avatar: https://avatars.githubusercontent.com/u/20763356?v=4&s=460
  description: "希望薯条宝宝一直健康快乐成长"
  weibo_username: 
  twitter_username: 
  github_username: shutiao2019
  zhihu_username: 
  douban_username: 
  linkedin_username: 

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcdn.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true